#!/bin/bash

ASMACK_RELEASES=http://asmack.freakempire.de/
# TODO There sure is a better way to extract the minSdkVersion attribute from an XML file
MIN_SDK_VERSION=$(grep minSdkVersion AndroidManifest.xml | awk -F"\"" '{print $2}')

if [[ -z $1 ]] ; then
    echo "Usage: $0 <aSmack_Version>"
    exit 1
fi

ASMACK_JAR=asmack-android-${MIN_SDK_VERSION}-${1}.jar
ASMACK_SRC=asmack-android-${MIN_SDK_VERSION}-source-${1}.zip

ASMACK_JAR_URL=${ASMACK_RELEASES}/${1}/${ASMACK_JAR}
ASMACK_SRC_URL=${ASMACK_RELEASES}/${1}/${ASMACK_SRC}

# First remove the old versions
git rm libs/asmack*.jar
git rm libs-sources/asmack*.zip

pushd .
cd libs
wget ${ASMACK_JAR_URL}
wget ${ASMACK_JAR_URL}.md5
md5sum -c ${ASMACK_JAR}.md5 || exit 1
rm ${ASMACK_JAR}.md5
git add ${ASMACK_JAR}
popd

pushd .
cd libs-sources
wget ${ASMACK_SRC_URL}
wget ${ASMACK_SRC_URL}.md5
md5sum -c ${ASMACK_SRC}.md5 || exit 1
rm ${ASMACK_SRC}.md5
git add ${ASMACK_SRC}
popd

sed -i \
    -e "s/asmack-android-.*jar/${ASMACK_JAR}/" \
    -e "s/sources\/asmack-android-.*zip/sources\/${ASMACK_SRC}/" \
    .classpath

git diff

